### ISSUE TITLE
package.json / typoの修正依頼

### ISSUE THREAD

**Issue by myonyomu** [nulab/franz-recipe-backlog#1]
backlogのユーザーとしてお世話になっております。

Franzを導入してbacklogへのログインを行おうとしたのですが、本プラグインを利用して一発で入れることができませんでした。
Franz version: 5.0.0.624

調べてみたところ、package.jsonの以下の項目のtypoが原因のようです。

現状
```
    "serviceURL": "https://{teamID}.backlog.com
```

修正
```
    "serviceURL": "https://{teamId}.backlog.com
```

プルリク作るまでもない問題だと思うので、お手すきの際にご対応いただければと思います。

**Comment by tsuyoshizawa** [comment]
ありがとうございます。修正しました。

Thank you for your report.
